name: 'Hexlet project action'
description: 'For testing projects'
inputs:
  project_image:
    description: 'Docker image from original project repository.'
    required: true
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project_image }}

