name: "test"
on:
  pull_request:
  push:
    branches:
      - master
      # - 'releases/*'

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make install
    - run: make test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make install
    - run: node server.js
    - uses: ./
      env:
        NODE_DEBUG: http
        HTTPS_PROXY: http://localhost:3000
      with:
        project-member-id: 1
        verbose: true
