name: "test"
on:
  pull_request:
  push:
    branches:
      - master
      # - 'releases/*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make install
    - run: make test
    - run: make lint

  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make install
    - run: node server.js &
    - uses: ./
      env:
        NODE_DEBUG: http
        ACTION_API_HOST: http://localhost:3000
        ACTION_PROJECT_PATH: __fixtures__/project_source
      with:
        hexlet-id: 1
        verbose: true

  artifacts:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: |
          test-results.zip
    - uses: actions/download-artifact@v4
      with:
        name: |
          test-data.zip
